"""add comment to post

Revision ID: 44767ee71e42
Revises: b2c7d703a715
Create Date: 2025-10-14 16:38:19.580266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44767ee71e42'
down_revision: Union[str, Sequence[str], None] = 'b2c7d703a715'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('comment', sa.String(), nullable=True))

    with op.batch_alter_table('request_filters', schema=None) as batch_op:
        batch_op.alter_column('year_from',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('year_to',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('odo_from',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('odo_to',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('document',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('transmission',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request_filters', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('transmission',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('document',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('odo_to',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('odo_from',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('year_to',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('year_from',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('comment')
        batch_op.drop_column('year')

    # ### end Alembic commands ###
