"""add stage to request table

Revision ID: 4657549275d2
Revises: ad03b432ff70
Create Date: 2025-10-02 16:20:44.504019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4657549275d2'
down_revision: Union[str, Sequence[str], None] = 'ad03b432ff70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request_filters', sa.Column('stage', sa.Enum('STARTING', 'FILTERING_BY_TEXT', 'GENERATION_IMAGES_DESCRIPTION', 'FILTERING_WITH_IMAGES_DESCRIPTION', 'COMPLETED', name='requeststage'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request_filters', 'stage')
    # ### end Alembic commands ###
