"""add new fields to post and request

Revision ID: 4b7c08afc72b
Revises: 8fcae0cce795
Create Date: 2025-11-06 02:04:16.492375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b7c08afc72b'
down_revision: Union[str, Sequence[str], None] = '8fcae0cce795'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('make', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('model', sa.String(), nullable=True))
        batch_op.drop_column('image_score')

    with op.batch_alter_table('request_filters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('drive', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('auction_time', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request_filters', schema=None) as batch_op:
        batch_op.drop_column('auction_time')
        batch_op.drop_column('drive')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_score', sa.INTEGER(), nullable=True))
        batch_op.drop_column('model')
        batch_op.drop_column('make')

    # ### end Alembic commands ###
