"""init

Revision ID: 5a6fa3941189
Revises: 
Create Date: 2025-09-24 14:07:23.137748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a6fa3941189'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request_filters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_uuid', sa.String(), nullable=False),
    sa.Column('site', sa.Enum('COPART', 'IAAI', name='auctionenum'), nullable=False),
    sa.Column('make', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('year_from', sa.Integer(), nullable=True),
    sa.Column('year_to', sa.Integer(), nullable=True),
    sa.Column('odo_from', sa.Integer(), nullable=True),
    sa.Column('odo_to', sa.Integer(), nullable=True),
    sa.Column('document', sa.String(), nullable=True),
    sa.Column('transmission', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=False),
    sa.Column('auction', sa.Enum('COPART', 'IAAI', name='auctionenum'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('odometer', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('reserve_price', sa.Integer(), nullable=True),
    sa.Column('vin', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('auction_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivery_price', sa.Integer(), nullable=False),
    sa.Column('shipping_price', sa.Integer(), nullable=False),
    sa.Column('average_sell_price', sa.Integer(), nullable=True),
    sa.Column('is_posted', sa.Boolean(), nullable=False),
    sa.Column('image_description', sa.String(), nullable=True),
    sa.Column('image_score', sa.Integer(), nullable=True),
    sa.Column('images', sa.String(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['request_filters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    op.drop_table('request_filters')
    # ### end Alembic commands ###
