"""add primary damage to post

Revision ID: 6a7f3316ec47
Revises: add_in_progress_to_requeststage
Create Date: 2025-10-13 17:33:11.906693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a7f3316ec47'
down_revision: Union[str, Sequence[str], None] = 'add_in_progress_to_requeststage'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('primary_damage', sa.String(), nullable=True))

    with op.batch_alter_table('request_filters', schema=None) as batch_op:
        batch_op.alter_column('stage',
               existing_type=sa.VARCHAR(length=33),
               type_=sa.Enum('FAILED', 'IN_PROGRESS', 'COMPLETED', name='requeststage'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request_filters', schema=None) as batch_op:
        batch_op.alter_column('stage',
               existing_type=sa.Enum('FAILED', 'IN_PROGRESS', 'COMPLETED', name='requeststage'),
               type_=sa.VARCHAR(length=33),
               existing_nullable=True)

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('primary_damage')

    # ### end Alembic commands ###
