"""add new enum

Revision ID: 6c53709783d2
Revises: 4657549275d2
Create Date: 2025-10-10 19:27:05.715219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c53709783d2'
down_revision: Union[str, Sequence[str], None] = '4657549275d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request_filters', schema=None) as batch_op:
        batch_op.alter_column('stage',
               existing_type=sa.VARCHAR(length=33),
               type_=sa.Enum('FAILED', 'IN_PROGRESS', 'COMPLETED', name='requeststage'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request_filters', schema=None) as batch_op:
        batch_op.alter_column('stage',
               existing_type=sa.Enum('FAILED', 'IN_PROGRESS', 'COMPLETED', name='requeststage'),
               type_=sa.VARCHAR(length=33),
               existing_nullable=True)

    # ### end Alembic commands ###
