"""make model nullable add auction date range to RequestFilters

Revision ID: ad03b432ff70
Revises: 5a6fa3941189
Create Date: 2025-09-29 13:07:45.231215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad03b432ff70'
down_revision: Union[str, Sequence[str], None] = '5a6fa3941189'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request_filters', sa.Column('auction_date_from', sa.DateTime(timezone=True), nullable=True))
    op.add_column('request_filters', sa.Column('auction_date_to', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('request_filters', 'model',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('request_filters', 'model',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('request_filters', 'auction_date_to')
    op.drop_column('request_filters', 'auction_date_from')
    # ### end Alembic commands ###
